"""Presenting a grammar through the existing language interface.

Nothing outside this package should have to know whether a language is realized
by the original template packs or by the grammar engine. Lessons, the CLI, the
site builder and the test suite all talk to
:class:`~langcurriculum.languages.base.Language`, so a grammar is wrapped in one.

Every language now goes through it. There is no template realizer left and no
code path that treats English differently from Swahili, which is the only way to
know the engine really carries the languages it claims to: if it regressed on
English, 2,200 tests would say so immediately.
"""

from __future__ import annotations

from typing import Any, Sequence

from .._structure import Term
from ..languages.base import Language, Lexicon
from ..languages.lexicon import Vocabulary
from .compile import classify, compile_episode
from .features import EMPTY
from .linearize import Grammar

__all__ = ["GrammarLanguage"]

#: what :func:`classify` calls a word -> the category the lexicon is keyed on.
#: ``word`` and ``sym`` have no part of speech and are looked up untyped.
_OPTION_POS = {"noun": "N", "adj": "A", "verb": "V"}


class GrammarLanguage(Language):
    """A :class:`~langcurriculum.grammar.linearize.Grammar` as a language pack."""

    kind = "natural"

    #: How many open-class entries a pack needs before it is considered to
    #: cover the curriculum rather than to sample it.
    FULL_VOCABULARY = 300

    def __init__(self, grammar: Grammar, *, description: str = ""):
        self.grammar = grammar
        self.code = grammar.code
        self.name = grammar.name
        self.description = description or f"{grammar.name}, generated by grammar."
        self.grammar_notes = tuple(grammar.notes)
        self.lexicon = self._build_lexicon()
        self._coverage: dict[str, int] | None = None

    def coverage(self) -> dict[str, int]:
        """Curriculum words this grammar has a word of its own for.

        Counted, not declared, and counted over the words the lessons can
        actually coin rather than over whatever a pack happened to write down.
        The old measure was ``len(lexicon.vocabulary)``, which a derived
        grammar leaves empty because its words are in a database — so all four
        hundred of them reported a vocabulary of zero and were classed as
        partial without anything having been measured.
        """
        if self._coverage is None:
            from .compile import classify, curriculum_vocabulary
            counts = {"nouns": 0, "adjectives": 0, "verbs": 0,
                      "names": 0, "words": 0, "total": 0}
            bucket = {"noun": "nouns", "adj": "adjectives", "verb": "verbs",
                      "word": "words", "sym": "names"}
            for key in curriculum_vocabulary():
                if self.grammar.knows(key):
                    counts[bucket.get(classify(key), "words")] += 1
                    counts["total"] += 1
            self._coverage = counts
        return dict(self._coverage)

    @property
    def partial_vocabulary(self) -> bool:
        """Computed, never declared — and now over something real.

        A pack may ship before it covers the whole curriculum; a grammar is
        useful with a partial lexicon and a lexicon is useless without a
        grammar. What it may not do is be quiet about it.
        """
        return self.coverage()["total"] < self.FULL_VOCABULARY

    def _build_lexicon(self) -> Lexicon:
        """Expose the grammar's lexical material through the old interface.

        The existing suite asserts real invariants over ``lang.lexicon`` — that
        no two identifiers collapse into one string, that a question keeps every
        argument it was given — and those are exactly the properties a new
        language most needs checked. Supplying the attribute is what lets those
        tests run against the engine rather than skipping it.
        """
        g = self.grammar
        typ = g.typography
        return Lexicon(
            definite=g.cw("the"), indefinite=g.cw("a"),
            copula_sg=g.cw("is"), copula_pl=g.cw("are"),
            negation=g.cw("not"), conjunction=g.cw("and"),
            then=g.cw("then") or "then",
            **{k: v for k, v in g.instructions.items()},
            disjunction=g.cw("or"), of=g.cw("of"),
            yes=g.word("yes"), no=g.word("no"),
            word_joiner=typ.word_joiner, capitalizes=typ.capitalizes,
            full_stop=typ.full_stop, question_mark=typ.question_mark,
            question_open=typ.question_open,
            list_separator=typ.list_separator,
            clause_separator=typ.clause_separator,
            arg_separator=typ.arg_separator, colon=typ.colon, bullet=typ.bullet,
            quantifiers={k: g.cw(k) for k in
                         ("all", "some", "none", "most", "few", "exactly_two")
                         if g.cw(k)},
            predicate_words=dict(g.predicate_words),
            field_intros=dict(g.field_intros),
            vocabulary=getattr(g, "vocabulary", Vocabulary()),
            # the held-out substitutions, where a grammar makes any: the
            # invariant tests need to recognise the word that reached the page
            synonyms=dict(getattr(g, "synonyms", {})),
            **{k: v for k, v in g.paradigms.items()},
        )

    # ---- the interface ---------------------------------------------------
    def render(self, term: Term) -> str:
        blocks, query = compile_episode(term)
        lines = [self.grammar.lin(b) for b in blocks]
        if query is not None:
            lines.append(self.grammar.question(query))
        return "\n".join(l for l in lines if l)

    def text(self, value: Any) -> str:
        """One leaf value as this language writes it.

        The same resolution the linearizer uses, exposed because the invariant
        tests compare what a word became in the prose against what it becomes
        here, and the two have to be the same function.
        """
        if not isinstance(value, str):
            return str(value)
        return self.grammar.word(value)

    def knows(self, value: str) -> bool:
        """Whether the option can be offered in this language at all."""
        return isinstance(value, str) and self.grammar.knows(value)

    def token(self, value: str) -> str:
        """Render one answer option in this language.

        Options must be in the prompt's language or the task silently becomes
        "translate, then answer". Words the grammar does not know pass through,
        which is most of them — object ids, nonce forms, numbers.

        The category comes from the same :func:`classify` the compiler uses to
        build the prompt, so an option is looked up as whatever part of speech
        the prose used it as. Asking untyped got the first sense a dictionary
        listed, and for *orange* that is a tree: Russian offered
        *апельси́новое де́рево* and German *Apfelsinenbaum* in a list of colours.
        """
        if not isinstance(value, str):
            return value
        return self.grammar.word(value, _OPTION_POS.get(classify(value), ""))

    def prompt(self, observation: str, choices: Sequence[str], *,
               max_inline: int = 40) -> str:
        g = self.grammar
        opts = [str(c) for c in choices]
        told = g.instructions
        instruction = told.get("instruction") or (
            "Answer with exactly one of: {choices}\nReply with the answer only.")
        if len(opts) <= max_inline:
            tail = instruction.format(choices=" | ".join(opts))
        else:
            listed = "\n".join(f"{g.typography.bullet}{o}" for o in opts)
            heading = told.get("options_heading") or "Options:"
            many = told.get("instruction_many") or (
                "Answer with exactly one of the {n} options listed above.\n"
                "Reply with the answer only.")
            tail = f"{heading}\n{listed}\n" + many.format(n=len(opts))
        return f"{observation}\n\n{tail}"

    def info(self) -> dict[str, Any]:
        base = self.grammar.info()
        base.update({"code": self.code, "name": self.name, "kind": self.kind,
                     "description": self.description,
                     "grammar": list(self.grammar_notes)})
        return base

    def __repr__(self) -> str:
        return f"<GrammarLanguage {self.code}>"
