"""``conservation_law_discovery`` — the expression the dynamics leave invariant.

Scientific induction and model discovery.
"""

from __future__ import annotations

import random
from typing import Sequence

from .._structure import Ident, Lst, Num, Pred, Rec, Term
from ..lesson import Lesson
from ..generators.science import _add, _eval, _labels, _mul, _shuffled, _sub


def gen_conservation_law_discovery(rng: random.Random, ctx):
    """Find the quantity the dynamics do not touch.

    The trajectory is generated by taking steps inside the null space of a
    randomly chosen weight vector, so ``w·state`` is conserved *by construction*
    rather than approximately; the five candidate expressions are then evaluated
    at every state on the trajectory and the episode is discarded unless exactly
    one of them is constant. The rivals include other linear combinations, which
    is the case that matters: a quantity that happens to be constant for two
    steps is not a conservation law.
    """
    for _ in range(400):
        w = [rng.choice([-2, -1, 1, 2]) for _ in range(3)]
        state = [rng.randint(-8, 8) for _ in range(3)]
        deltas = []
        for _ in range(200):
            d = [rng.randint(-3, 3) for _ in range(3)]
            if any(d) and sum(wi * di for wi, di in zip(w, d)) == 0:
                deltas.append(d)
            if len(deltas) == 5:
                break
        if len(deltas) < 5:
            continue
        traj = [tuple(state)]
        for d in deltas:
            traj.append(tuple(s + di for s, di in zip(traj[-1], d)))
        names = ["a", "b", "c"]

        def linear(ws: Sequence[int]) -> Term:
            return _add(_add(_mul(Num(ws[0]), Ident("a")), _mul(Num(ws[1]), Ident("b"))),
                        _mul(Num(ws[2]), Ident("c")))

        n_linear = ctx.at(3, 7, default=3)          # rival linear combinations, incl. the true one
        cands = [linear(w)]
        for _ in range(40):
            ws = [rng.choice([-2, -1, 0, 1, 2]) for _ in range(3)]
            if any(ws) and ws != w and linear(ws) not in cands:
                cands.append(linear(ws))
            if len(cands) == n_linear:
                break
        cands.append(_mul(Ident("a"), Ident("b")))
        cands.append(Pred("abs", _sub(Ident("a"), Ident("c"))))
        if len(cands) != n_linear + 2:
            continue
        envs = [{"a": s[0], "b": s[1], "c": s[2]} for s in traj]
        const = [i for i, ex in enumerate(cands)
                 if len({_eval(ex, e) for e in envs}) == 1]
        if const != [0]:
            continue
        order = _shuffled(rng, range(len(cands)))
        labels = _labels("k", len(cands))
        answer = labels[order.index(0)]
        obs = Rec(trajectory=Lst([Pred("state", Num(s[0]), Num(s[1]), Num(s[2])) for s in traj]),
                  variables=Lst([Ident(v) for v in names]),
                  candidates=Lst([Pred("quantity", Ident(labels[j]), cands[i])
                                  for j, i in enumerate(order)]),
                  query=Ident("conserved_quantity"))
        hidden = {"weights": w, "value": _eval(cands[0], envs[0]), "answer": answer}
        return obs, _shuffled(rng, labels), answer, hidden
    raise RuntimeError("conservation_law_discovery: no admissible episode")


class ConservationLawDiscovery(Lesson):
    """The expression the dynamics leave invariant."""

    id = "conservation_law_discovery"
    level = 79
    tags = ("science", "induction", "model-discovery")
    teaches = "the expression the dynamics leave invariant"
    capabilities = ('scientific_induction', 'abstraction', 'program_synthesis')
    axes = {'reasoning_depth': 5, 'compositional_depth': 4, 'world_complexity': 3}

    generate = staticmethod(gen_conservation_law_discovery)
