import type { AppManifest, OSKind } from '@tcn-computer/protocol';

export type SurfaceLayout = 'document' | 'split-view' | 'three-pane' | 'canvas' | 'dashboard' | 'conversation' | 'media' | 'utility' | 'viewport';

export interface ApplicationSurfaceDefinition {
  id: string;
  appIds: readonly string[];
  layout: SurfaceLayout;
  regions: readonly string[];
  interactions: readonly string[];
  stateSources: readonly ('vfs' | 'processes' | 'network' | 'packages' | 'service' | 'local-ui' | 'peripherals')[];
  platformAdapters: readonly OSKind[];
  identityRule: string;
}

function surface(value: ApplicationSurfaceDefinition): ApplicationSurfaceDefinition {
  if (!value.appIds.length) throw new Error(`${value.id}: surface has no applications`);
  if (!value.interactions.length) throw new Error(`${value.id}: surface has no interactions`);
  return Object.freeze(value);
}

export const applicationSurfaces: readonly ApplicationSurfaceDefinition[] = [
  surface({ id: 'files', appIds: ['finder', 'explorer', 'nautilus'], layout: 'split-view', regions: ['platform sidebar', 'location toolbar', 'file collection', 'status'], interactions: ['navigate', 'search', 'switch view', 'open directory'], stateSources: ['vfs', 'network'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use Finder, File Explorer, and GNOME Files navigation taxonomies independently.' }),
  surface({ id: 'terminal', appIds: ['terminal'], layout: 'document', regions: ['tabs', 'scrollback', 'prompt'], interactions: ['execute', 'history', 'interrupt'], stateSources: ['vfs', 'processes', 'network', 'packages'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Render zsh, PowerShell, or bash according to the computer profile.' }),
  surface({ id: 'settings', appIds: ['settings'], layout: 'split-view', regions: ['platform categories', 'setting detail'], interactions: ['search', 'select category', 'toggle policy'], stateSources: ['network', 'peripherals', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'System Settings, Windows Settings, and GNOME Settings use separate terminology.' }),
  surface({ id: 'editors', appIds: ['textedit', 'notepad', 'gedit'], layout: 'document', regions: ['native menu', 'format or tab strip', 'editor', 'status'], interactions: ['edit', 'save', 'wrap', 'format'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Preserve each editor’s native density and command placement.' }),
  surface({ id: 'document-preview', appIds: ['preview', 'document-viewer'], layout: 'split-view', regions: ['thumbnails', 'page controls', 'document stage'], interactions: ['select page', 'zoom', 'export'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['macos', 'ubuntu'], identityRule: 'Preview and Evince retain their native toolbar hierarchy.' }),
  surface({ id: 'photos', appIds: ['photos'], layout: 'split-view', regions: ['library navigation', 'asset grid', 'selection metadata'], interactions: ['browse', 'select', 'favorite', 'filter'], stateSources: ['vfs', 'peripherals', 'local-ui'], platformAdapters: ['macos', 'windows'], identityRule: 'Adapt selection and navigation chrome to the host OS.' }),
  surface({ id: 'calculator', appIds: ['calculator'], layout: 'utility', regions: ['mode', 'display', 'history', 'keypad'], interactions: ['enter digits', 'operate', 'clear', 'copy'], stateSources: ['local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use host typography while preserving calculator key semantics.' }),
  surface({ id: 'calendar', appIds: ['calendar'], layout: 'split-view', regions: ['calendar list', 'period toolbar', 'time grid', 'agenda'], interactions: ['change period', 'select day', 'create event'], stateSources: ['service', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Calendar service state is shared; platform controls are not.' }),
  surface({ id: 'mail', appIds: ['mail'], layout: 'three-pane', regions: ['mailboxes', 'message list', 'reader'], interactions: ['search', 'select message', 'compose', 'archive'], stateSources: ['service', 'local-ui'], platformAdapters: ['macos', 'ubuntu'], identityRule: 'Use the Seed Mail service through a native platform client.' }),
  surface({ id: 'outlook', appIds: ['outlook'], layout: 'three-pane', regions: ['Microsoft app rail', 'folder list', 'message list', 'reader'], interactions: ['search', 'select message', 'compose', 'archive'], stateSources: ['service', 'local-ui'], platformAdapters: ['windows'], identityRule: 'Follow Outlook navigation rather than the generic Mail shell.' }),
  surface({ id: 'mac-app-store', appIds: ['app-store'], layout: 'split-view', regions: ['App Store navigation', 'editorial feature', 'app rows'], interactions: ['search', 'browse', 'install', 'update'], stateSources: ['service', 'packages', 'vfs'], platformAdapters: ['macos'], identityRule: 'Use macOS App Store language and GET actions.' }),
  surface({ id: 'microsoft-store', appIds: ['store'], layout: 'split-view', regions: ['Store navigation', 'feature', 'catalog'], interactions: ['search', 'browse', 'install', 'open library'], stateSources: ['service', 'packages', 'vfs'], platformAdapters: ['windows'], identityRule: 'Use Microsoft Store navigation and sentence-case actions.' }),
  surface({ id: 'ubuntu-app-center', appIds: ['app-center'], layout: 'split-view', regions: ['App Center navigation', 'editorial feature', 'catalog'], interactions: ['search', 'browse', 'install', 'update'], stateSources: ['service', 'packages', 'vfs'], platformAdapters: ['ubuntu'], identityRule: 'Represent deb, snap, and repository provenance.' }),
  surface({ id: 'browsers', appIds: ['chromium', 'safari', 'edge', 'firefox'], layout: 'document', regions: ['tab strip', 'navigation toolbar', 'web content', 'network status'], interactions: ['navigate', 'back', 'forward', 'reload', 'new tab'], stateSources: ['network', 'vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Each browser retains its own new-tab identity and control order.' }),
  surface({ id: 'slack', appIds: ['slack'], layout: 'three-pane', regions: ['Slack rail', 'workspace navigation', 'channel header', 'messages', 'composer'], interactions: ['select channel', 'poll', 'send', 'huddle'], stateSources: ['service', 'network'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Only communicate with slack.seed.local.' }),
  surface({ id: 'teams', appIds: ['teams'], layout: 'three-pane', regions: ['Teams app rail', 'team tree', 'channel tabs', 'posts', 'composer'], interactions: ['select team', 'poll', 'post', 'meet'], stateSources: ['service', 'network'], platformAdapters: ['macos', 'windows'], identityRule: 'Only communicate with teams.seed.local; never bridge Slack state.' }),
  surface({ id: 'chatgpt', appIds: ['chatgpt'], layout: 'three-pane', regions: ['conversation navigation', 'thread', 'composer', 'work inspector'], interactions: ['switch mode', 'send', 'attach', 'run tool'], stateSources: ['service', 'vfs', 'network', 'local-ui'], platformAdapters: ['macos'], identityRule: 'Consumer Chat and professional Work are modes of one product.' }),
  surface({ id: 'vscode', appIds: ['vscode'], layout: 'three-pane', regions: ['activity bar', 'explorer', 'tabs', 'editor', 'status'], interactions: ['open file', 'edit', 'save', 'run task'], stateSources: ['vfs', 'processes', 'network'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Follow Visual Studio Code workbench structure.' }),
  surface({ id: 'cursor', appIds: ['cursor'], layout: 'three-pane', regions: ['explorer', 'editor', 'agent panel', 'status'], interactions: ['open file', 'edit', 'save', 'run agent'], stateSources: ['vfs', 'processes', 'network', 'service'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Expose Cursor’s agent affordance rather than a rebadged VS Code surface.' }),
  surface({ id: 'wireshark', appIds: ['wireshark'], layout: 'three-pane', regions: ['capture toolbar', 'packet list', 'packet detail', 'bytes'], interactions: ['capture', 'filter', 'select packet', 'export'], stateSources: ['network', 'vfs'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Rows project actual simulation packet traces.' }),
  surface({ id: 'messages', appIds: ['messages'], layout: 'split-view', regions: ['conversation list', 'thread', 'composer'], interactions: ['select conversation', 'send', 'start call'], stateSources: ['service', 'network'], platformAdapters: ['macos'], identityRule: 'Use Messages conversation behavior and Apple-style contact hierarchy.' }),
  surface({ id: 'discord', appIds: ['discord'], layout: 'three-pane', regions: ['server rail', 'channel tree', 'messages', 'member list'], interactions: ['select channel', 'send', 'start voice'], stateSources: ['service', 'network'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Preserve guild/channel/member structure.' }),
  surface({ id: 'facetime', appIds: ['facetime'], layout: 'viewport', regions: ['recent calls', 'camera preview', 'call controls'], interactions: ['start call', 'mute', 'toggle camera', 'end'], stateSources: ['service', 'network', 'peripherals'], platformAdapters: ['macos'], identityRule: 'Use FaceTime contact-first call flow.' }),
  surface({ id: 'zoom', appIds: ['zoom'], layout: 'viewport', regions: ['meeting lobby', 'participant grid', 'meeting controls'], interactions: ['join', 'mute', 'toggle camera', 'share', 'leave'], stateSources: ['service', 'network', 'peripherals'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use Zoom meeting semantics and terminology.' }),
  surface({ id: 'music-libraries', appIds: ['music', 'rhythmbox', 'spotify'], layout: 'media', regions: ['library navigation', 'feature', 'track list', 'player'], interactions: ['browse', 'select track', 'play', 'pause', 'seek'], stateSources: ['service', 'vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Keep Apple Music, Rhythmbox, and Spotify branding and library taxonomies distinct.' }),
  surface({ id: 'vlc', appIds: ['vlc'], layout: 'media', regions: ['native menu', 'video stage', 'transport'], interactions: ['open', 'play', 'pause', 'seek'], stateSources: ['vfs', 'network', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use VLC desktop transport, not a streaming-library shell.' }),
  surface({ id: 'audacity', appIds: ['audacity'], layout: 'canvas', regions: ['menus', 'transport', 'timeline', 'tracks', 'status'], interactions: ['record', 'play', 'mute track', 'edit'], stateSources: ['vfs', 'peripherals', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Model multitrack editing and recording state.' }),
  surface({ id: 'maps', appIds: ['maps'], layout: 'split-view', regions: ['search and favorites', 'map', 'place card'], interactions: ['search', 'select place', 'route', 'save'], stateSources: ['service', 'network', 'local-ui'], platformAdapters: ['macos'], identityRule: 'Use map-space interaction rather than generic result cards.' }),
  surface({ id: 'reminders', appIds: ['reminders'], layout: 'split-view', regions: ['lists', 'task list'], interactions: ['create', 'complete', 'schedule'], stateSources: ['service', 'local-ui'], platformAdapters: ['macos'], identityRule: 'Use list and scheduled-reminder semantics.' }),
  surface({ id: 'linear', appIds: ['linear'], layout: 'dashboard', regions: ['workspace navigation', 'issue toolbar', 'issue table'], interactions: ['filter', 'create issue', 'change status'], stateSources: ['service', 'network'], platformAdapters: ['macos', 'windows'], identityRule: 'Use projects, cycles, issue IDs, and statuses.' }),
  surface({ id: 'paint', appIds: ['paint'], layout: 'canvas', regions: ['ribbon', 'palette', 'canvas', 'status'], interactions: ['select tool', 'draw', 'undo', 'save'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['windows'], identityRule: 'Use Paint’s ribbon and simple raster workflow.' }),
  surface({ id: 'snipping-tool', appIds: ['snipping-tool'], layout: 'canvas', regions: ['capture toolbar', 'capture preview', 'annotation toolbar'], interactions: ['capture region', 'annotate', 'copy', 'save'], stateSources: ['vfs', 'peripherals', 'local-ui'], platformAdapters: ['windows'], identityRule: 'Use a capture-first workflow.' }),
  surface({ id: 'gimp', appIds: ['gimp'], layout: 'three-pane', regions: ['toolbox', 'canvas', 'layers', 'tool options'], interactions: ['select tool', 'draw', 'select layer', 'export'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use GIMP’s toolbox/layers model.' }),
  surface({ id: 'processes', appIds: ['task-manager', 'system-monitor'], layout: 'dashboard', regions: ['navigation', 'resource summary', 'process table'], interactions: ['search', 'sort', 'inspect', 'terminate'], stateSources: ['processes'], platformAdapters: ['windows', 'ubuntu'], identityRule: 'Use Task Manager or GNOME System Monitor terminology per host.' }),
  surface({ id: 'packages', appIds: ['package-center', 'software-updater'], layout: 'dashboard', regions: ['manager navigation', 'summary', 'package table'], interactions: ['filter manager', 'search', 'check updates', 'install'], stateSources: ['packages', 'vfs', 'network'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Receipts and transactions must agree with shell package commands.' }),
  surface({ id: 'git-clients', appIds: ['github-desktop', 'gitkraken'], layout: 'three-pane', regions: ['repositories', 'changes or graph', 'commit detail'], interactions: ['select repository', 'stage', 'commit', 'branch', 'push'], stateSources: ['vfs', 'network'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Preserve each client’s graph/history emphasis.' }),
  surface({ id: 'docker-desktop', appIds: ['docker-desktop'], layout: 'dashboard', regions: ['resource navigation', 'engine status', 'container table'], interactions: ['search', 'start', 'stop', 'inspect'], stateSources: ['processes', 'network', 'vfs'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Model containers, images, volumes, and networks explicitly.' }),
  surface({ id: 'postman', appIds: ['postman'], layout: 'three-pane', regions: ['collections', 'request builder', 'response'], interactions: ['select request', 'edit URL', 'send', 'save'], stateSources: ['network', 'vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use request/response workflow and trace the virtual HTTP exchange.' }),
  surface({ id: 'figma', appIds: ['figma'], layout: 'three-pane', regions: ['layers', 'canvas', 'properties'], interactions: ['select layer', 'move', 'resize', 'edit property'], stateSources: ['service', 'vfs', 'local-ui'], platformAdapters: ['macos', 'windows'], identityRule: 'Use Figma layer/canvas/inspector structure.' }),
  surface({ id: 'blender', appIds: ['blender'], layout: 'viewport', regions: ['outliner', '3D viewport', 'properties', 'timeline'], interactions: ['select object', 'change mode', 'transform', 'play timeline'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use Blender workspaces and a navigable 3D scene.' }),
  surface({ id: 'notion', appIds: ['notion'], layout: 'split-view', regions: ['workspace tree', 'page editor'], interactions: ['select page', 'edit blocks', 'search', 'share'], stateSources: ['service', 'network', 'local-ui'], platformAdapters: ['macos', 'windows'], identityRule: 'Use pages and blocks.' }),
  surface({ id: 'obsidian', appIds: ['obsidian'], layout: 'three-pane', regions: ['vault tree', 'Markdown editor', 'backlinks'], interactions: ['select note', 'edit', 'search', 'navigate link'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use local vault, links, and graph semantics.' }),
  surface({ id: 'libreoffice', appIds: ['libreoffice'], layout: 'document', regions: ['menus', 'format toolbar', 'page', 'status'], interactions: ['edit', 'format', 'save', 'export'], stateSources: ['vfs', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use office-document pagination and formatting controls.' }),
  surface({ id: 'steam', appIds: ['steam'], layout: 'split-view', regions: ['global navigation', 'library', 'game detail', 'activity'], interactions: ['select title', 'install', 'launch', 'stop'], stateSources: ['service', 'network', 'packages', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use Steam library and game lifecycle state.' }),
  surface({ id: 'vaults', appIds: ['bitwarden', 'onepassword'], layout: 'split-view', regions: ['lock screen', 'vault navigation', 'item list'], interactions: ['unlock', 'search', 'copy field', 'lock'], stateSources: ['service', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Keep vault contents behind an explicit lock boundary and preserve product vocabulary.' }),
  surface({ id: 'dbeaver', appIds: ['dbeaver'], layout: 'three-pane', regions: ['database navigator', 'SQL editor', 'result grid'], interactions: ['connect', 'browse schema', 'query', 'commit'], stateSources: ['service', 'network', 'local-ui'], platformAdapters: ['macos', 'windows', 'ubuntu'], identityRule: 'Use database connection and query semantics.' }),
];

export function surfaceForApp(appId: string): ApplicationSurfaceDefinition | undefined {
  return applicationSurfaces.find((definition) => definition.appIds.includes(appId));
}

export function validateSurfaceCoverage(apps: readonly Pick<AppManifest, 'id' | 'supportedOS' | 'operations'>[]): string[] {
  const findings: string[] = [];
  const assignments = new Map<string, string[]>();
  for (const definition of applicationSurfaces) {
    for (const appId of definition.appIds) assignments.set(appId, [...(assignments.get(appId) ?? []), definition.id]);
  }
  for (const app of apps) {
    const surfaces = assignments.get(app.id) ?? [];
    if (!surfaces.length) findings.push(`${app.id}: no UI surface definition`);
    if (surfaces.length > 1) findings.push(`${app.id}: assigned to multiple surfaces (${surfaces.join(', ')})`);
    const definition = surfaceForApp(app.id);
    for (const os of app.supportedOS) if (definition && !definition.platformAdapters.includes(os)) findings.push(`${app.id}: surface ${definition.id} has no ${os} adapter`);
  }
  for (const appId of assignments.keys()) if (!apps.some((app) => app.id === appId)) findings.push(`${appId}: surface references an unknown application`);
  return findings;
}
